M48
; DRILL file {KiCad 6.0.2-378541a8eb~116~ubuntu20.04.1} date Po 7. března 2022, 20:24:24
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-03-07T20:24:24+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.2-378541a8eb~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X2.479Y-3.7114
X3.266Y-3.7114
T0
M30
