M48
; DRILL file {KiCad 6.0.2-378541a8eb~116~ubuntu20.04.1} date Po 28. února 2022, 20:37:30
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-02-28T20:37:30+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.2-378541a8eb~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1181
%
G90
G05
T1
X0.0Y0.0
X0.0Y-1.175
X1.475Y0.0
X1.475Y-1.175
T0
M30
